import type { Metadata } from "next";
import { Kaushan_Script, Roboto } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/provider/ReduxProvider";
import AuthProvider from "@/provider/AuthProvider";
import { MainLayout } from "@/layouts/MainLayout";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["100", "300", "400", "500", "700", "900"],
});

const kaushanScript = Kaushan_Script({
  subsets: ["latin"],
  variable: "--font-kaushan-script",
  weight: ["400"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${kaushanScript.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <ReduxProvider>
          <AuthProvider>
            <MainLayout>{children}</MainLayout>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
